# MY FIRST Dockerfile Configuration
FROM ubuntu:18.04
MAINTAINER c0nstant sangsoo@horangi.com

RUN apt-get update
RUN apt-get -y upgrade
RUN apt install wget
RUN wget https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz
RUN 
